name: flutter_cafeteria_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^1.0.0
  flutter_markdown: ^0.7.7+1
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: IBMPlexSansJP
      fonts:
        - asset: assets/fonts/IBMPlexSansJP-Thin.ttf
          weight: 100
        - asset: assets/fonts/IBMPlexSansJP-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexSansJP-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansJP-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSansJP-Bold.ttf
          weight: 700